### ISSUE TITLE
Not able to use eth-graphql in NextJS App

### ISSUE THREAD

**Issue by victoryeo** [therealemjy/eth-graphql#2] opened 2023-11-25 12:51 UTC
The errors are as below.
 
 ⨯ file:///home/workspace/nextjs-app/node_modules/eth-graphql/dist/index.mjs:6
import { ApolloLink, Observable } from "@apollo/client";
         ^^^^^^^^^^
SyntaxError: Named export 'ApolloLink' not found. The requested module '@apollo/client' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@apollo/client';
const { ApolloLink, Observable } = pkg;

**Comment by victoryeo** [comment] 2023-11-25 13:11
To make it work
I edit the file:
node_modules/eth-graphql/dist/index.mjs
and edit line 6 to become:
import { ApolloLink, Observable } from "@apollo/client/core/index.js";

**Comment by therealemjy** [comment] 2023-11-25 14:14
Hi @victoryeo 
What version of `@apollo/client` are you using?

For a working example using NextJS, you can check the [example](https://github.com/therealemjy/eth-graphql/tree/main/example) app.

**Comment by victoryeo** [comment] 2023-11-26 12:21
>> What version of @apollo/client are you using?  

3.8.7

>> For a working example using NextJS, you can check the (https://github.com/therealemjy/eth-graphql/tree/main/example) app.  

"yarn dev" is not working on the example app. The error is:  Cannot find module './eth-graphql/node_modules/eth-graphql/dist/index.js'

But i am able to use eth graphql in my nextjs code. It is at: https://github.com/victoryeo/nextjs-app

**Comment by victoryeo** [comment] 2023-11-29 07:17
i am using node version 18.
any feedback on the error in the example app?

**Comment by therealemjy** [comment] 2023-11-29 09:14
I'm unable to reproduce the issue you face with the example app.

If you're able to use eth-graphql in your project however then I think we can close this issue.

**Closed as completed** 2024-02-28 14:33 UTC
